spin_version = "1"
authors = ["Khoi Nguyen Van <khoinv@smartosc.com>"]
description = "A webAssembly builded by Golang, run on Spin runtime"
name = "go-spin"
trigger = { type = "http", base = "/" }
version = "0.1.0"

[[component]]
id = "go-spin"
source = "main.wasm"
allowed_http_hosts = []
[component.trigger]
route = "/..."
[component.build]
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
