spin_manifest_version = "1"
authors = ["pc-home <pc@home>"]
description = ""
name = "csharp-spin"
version = "1.0.0"
trigger = { type = "http", base = "/" }

[[component]]
id = "csharp_spin"
source = "bin/Release/net7.0/CsharpSpin.wasm"
[component.build]
command = "dotnet build -c Release"
[component.trigger]
route = "/..."
